# Generated by Django 6.0 on 2026-02-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task_category_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
