# Generated by Django 6.0.2 on 2026-02-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_task_is_deleted_alter_task_deadline_delete_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Study', 'Study'), ('Personal', 'Personal'), ('Health', 'Health'), ('Finance', 'Finance'), ('Other', 'Other')], default='Work', max_length=20),
        ),
    ]
